# Generated by Django 4.2.7 on 2023-11-30 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='profile',
        ),
    ]
